name: SonarCloud
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt pytest-cov
      - run: pytest --cov=pages --cov-report=xml
      - uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: a910b6700bc045dd259d61986e7b7f3b3446addf
